apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator-api.fullname" . }}
  labels:
    {{- include "calculator-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calculator-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calculator-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.DATABASE_URL }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
